FROM node:12-alpine AS builder
ENV HOST 0.0.0.0

RUN mkdir -p /app
COPY . /app
WORKDIR /app

RUN npm install
RUN npm run generate

FROM nginx:1.13-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80


